version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: userdb_dev
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: userdb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 20s

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server_dev
    restart: always
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=mysql://root:my-secret-pw@mysql:3306/userdb
    depends_on: 
      mysql:
        condition: service_healthy
    volumes:
      - ./server:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]  

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client_dev
    restart: always
    ports:
      - "3000:3000"  
    volumes:
      - ./client:/app
      - /app/node_modules
    command: ["npm" , "run" ,"start"]  

volumes:
  mysql_data:
